service: meme-maker

custom:
  bucket: kekmeme  #must be aws wide unique

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  #profile: #uncomment and set profile name if using non-default aws profile

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.bucket}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:GetObject"
        - "s3:GetObjectAcl"
        - "s3:DeleteObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  meme:
    handler: handler.handler
    environment:
      bucket: ${self:custom.bucket}
    events:
      - http:
          path: ${self:service}
          method: POST

resources:
  Resources:
    MemeBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucket}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

plugins:
  - serverless-python-requirements
